[PLAT-296] Remove scheme trimming from step-danger
bitrise-steplib/steps-danger pull request #13
Opened 2020-08-31 14:59 UTC by adborbas

2020-08-31 18:56 UTC, orta commented
that's shipped on 8.0.5

2020-09-01 09:49 UTC, lpusok requested changes

2020-09-01 09:49 UTC, lpusok commented on main.go
> +func trimmScheme(url string) string {
Typo in `trimm`, should be trim.

2020-09-01 09:49 UTC, lpusok commented on main.go
> +		log.Errorf("Could not determin danger vesion: %s", err)
Typo in `determin`, should be determine.

2020-09-01 09:49 UTC, lpusok commented on main.go
> +	rawDangerVersion, err := exec.Command("danger", "--version").CombinedOutput()
Please use log the command executed (recommended to use the command package).

2020-09-01 10:10 UTC, lpusok requested changes
Some typos remained.

2020-09-01 10:10 UTC, lpusok commented on main.go
> +		log.Errorf("Could not determin danger vesion: %s", err)
It is not updated.

2020-09-01 10:10 UTC, lpusok commented on main.go
> +// trimScheme trimms the URL if danger version is <8.0.5
There is a trimm remaining :)

2020-09-01 10:19 UTC, lpusok approved these changes

2020-09-01 10:25 UTC, merged